// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-N0cMFdmWZIfj3ciQQOVWzy3OfMt_IHQ',
    appId: '1:340026377526:web:a3c2ac7987a74178c85f97',
    messagingSenderId: '340026377526',
    projectId: 'narouto-store',
    authDomain: 'narouto-store.firebaseapp.com',
    storageBucket: 'narouto-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRxAUz608tIpFx1DSJFUU8Hm6P9V3NqQM',
    appId: '1:340026377526:android:3f7804e0f1786cf5c85f97',
    messagingSenderId: '340026377526',
    projectId: 'narouto-store',
    storageBucket: 'narouto-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0mQ812ZLBcYyW8BPO358Bb4PPam1KZmY',
    appId: '1:340026377526:ios:48fe9c2c8c0905d4c85f97',
    messagingSenderId: '340026377526',
    projectId: 'narouto-store',
    storageBucket: 'narouto-store.appspot.com',
    iosBundleId: 'com.example.naroutoshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0mQ812ZLBcYyW8BPO358Bb4PPam1KZmY',
    appId: '1:340026377526:ios:024c6d56f7b9b5e8c85f97',
    messagingSenderId: '340026377526',
    projectId: 'narouto-store',
    storageBucket: 'narouto-store.appspot.com',
    iosBundleId: 'com.example.naroutoshop.RunnerTests',
  );
}
